name = "spinmamaapp-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmamaapp.es"
HMAC_KEY = "e4a2e2344b2d4862a162ca2675b77787ae89b4e5283157c906f75cdbf94265c1"
COOKIE_NAME = "nkt"
PLAY_PATH = "visit"
BUTTON_ID = "p5a30e594b7732379bad623e95d34346c"
GATE_SALT = "d37df117cec6dfbb"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "4q1u"
CTA_SELECTOR = ".play-button"
